import { Inter } from "next/font/google";
import "./globals.css";
import NavBar from "../components/NavBar";
import UserContextProvider from "@/context/UserContex";

const inter = Inter({ subsets: ["latin"] });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <UserContextProvider>
          <NavBar />
          {children}
        </UserContextProvider>
      </body>
    </html>
  );
}
